import type { Schema } from '../../types';

/**
 * Structural validators. Credentials = `{ bot_token }`; the `secret_token`
 * for the webhook header is generated by `connect` and merged in afterwards.
 * Config has no required keys (config keys matching /token|secret|.../ are
 * hidden from clients, so none are used here).
 */

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

export interface TelegramConfig {
  bot_username?: string;
  [key: string]: unknown;
}

export interface TelegramCredentials {
  bot_token: string;
  secret_token?: string;
}

export const telegramConfigSchema: Schema<TelegramConfig> = {
  safeParse(input) {
    if (!isRecord(input)) {
      return { success: false, error: 'config must be an object' };
    }
    if (
      input.bot_username !== undefined &&
      (typeof input.bot_username !== 'string' || !input.bot_username.trim())
    ) {
      return {
        success: false,
        error: 'bot_username must be a non-empty string',
      };
    }
    return { success: true, data: input as TelegramConfig };
  },
};

export const telegramCredentialsSchema: Schema<TelegramCredentials> = {
  safeParse(input) {
    if (
      !isRecord(input) ||
      typeof input.bot_token !== 'string' ||
      !/^\S+$/.test(input.bot_token)
    ) {
      return { success: false, error: 'bot_token is required' };
    }
    return { success: true, data: { bot_token: input.bot_token } };
  },
};
